import { createHash } from "node:crypto";
import {
  operatorSecretsMatch,
  RuntimeError,
  type MissionRuntime,
  type ArtifactRepository,
  type MissionRecord,
} from "@truaxiom/core";
import type { RuntimeApiRequest } from "./missionRuntimeApi";
export interface WorkerCredential {
  agent_id: string;
  key_sha256: string;
}
/** Configuration stores digests, not bearer keys. No credentials are generated by this release. */
export function readWorkerCredentials(value?: string): WorkerCredential[] {
  if (!value) return [];
  const entries: unknown = JSON.parse(value);
  if (
    !Array.isArray(entries) ||
    entries.some(
      (e) =>
        !e ||
        Object.keys(e).sort().join(",") !== "agent_id,key_sha256" ||
        !/^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$/.test(e.agent_id) ||
        !/^[a-f0-9]{64}$/.test(e.key_sha256),
    )
  )
    throw new Error("Invalid runtime worker credential configuration");
  const hashes = entries.map((e) => e.key_sha256);
  if (new Set(hashes).size !== hashes.length)
    throw new Error("Duplicate runtime worker credentials");
  return entries;
}
function redact(r: MissionRecord, reveal = false) {
  const copy = structuredClone(r);
  copy.receipts = {};
  if (copy.lease && !reveal) copy.lease.token = "REDACTED";
  return copy;
}
export function createRuntimeWorkerApi(
  runtime: MissionRuntime,
  artifacts: ArtifactRepository,
  credentials: WorkerCredential[],
) {
  return async (
    request: RuntimeApiRequest,
  ): Promise<{ status: number; body: unknown }> => {
    const token =
      request.headers?.authorization?.match(/^Bearer\s+(\S+)$/i)?.[1];
    const digest = token
      ? createHash("sha256").update(token).digest("hex")
      : "";
    const credential = credentials.find(
      (c) => digest && operatorSecretsMatch(digest, c.key_sha256),
    );
    if (!credential)
      return { status: 401, body: { error: "Worker authentication required" } };
    const principal = { actor: credential.agent_id, role: "agent" as const };
    try {
      if (
        request.path === "/v1/runtime/worker/missions" &&
        request.method === "GET"
      )
        return {
          status: 200,
          body: {
            missions: (await runtime.repository.list())
              .filter(
                (r) =>
                  r.delegation.assigned_agent_id === principal.actor ||
                  r.handoffs.some(
                    (h) =>
                      h.status === "PENDING" &&
                      h.to_agent_id === principal.actor,
                  ),
              )
              .map((r) => redact(r)),
          },
        };
      const match = request.path.match(
        /^\/v1\/runtime\/worker\/missions\/([^/]+)(?:\/(commands|artifacts))?$/,
      );
      if (!match)
        return { status: 404, body: { error: "Worker route not found" } };
      let id: string;
      try {
        id = decodeURIComponent(match[1]);
      } catch {
        throw new RuntimeError(400, "Invalid path encoding");
      }
      const record = await runtime.get(id);
      if (
        record.delegation.assigned_agent_id !== principal.actor &&
        !record.handoffs.some(
          (h) => h.status === "PENDING" && h.to_agent_id === principal.actor,
        )
      )
        throw new RuntimeError(403, "Mission outside worker assignment");
      if (request.method === "GET" && !match[2])
        return { status: 200, body: redact(record) };
      if (request.method === "POST" && match[2] === "commands") {
        const r = await runtime.command(id, request.body, principal);
        const cmd = request.body as {
          type?: string;
          attempt_id?: string;
          lease_token?: string;
        };
        const reveal =
          r.lease?.agent_id === principal.actor &&
          ((cmd.type === "claim" && cmd.attempt_id === r.lease.attempt_id) ||
            cmd.lease_token === r.lease.token);
        return { status: 200, body: redact(r, reveal) };
      }
      if (request.method === "POST" && match[2] === "artifacts") {
        const b = request.body as Record<string, unknown>;
        if (
          !b ||
          Object.keys(b).sort().join(",") !== "content,kind,lease_token" ||
          b.kind !== "repository-report" ||
          !b.content ||
          typeof b.content !== "object" ||
          Array.isArray(b.content)
        )
          throw new RuntimeError(400, "Invalid artifact payload");
        if (
          record.delegation.status !== "RUNNING" ||
          record.lease?.agent_id !== principal.actor ||
          record.lease?.token !== b.lease_token ||
          Date.parse(record.lease.expires_at) <= Date.now()
        )
          throw new RuntimeError(403, "Valid running lease required");
        return {
          status: 200,
          body: {
            sha256: await artifacts.put({
              schema_version: "1.0",
              mission_id: id,
              kind: String(b.kind),
              content: b.content as Record<string, unknown>,
            }),
          },
        };
      }
      return { status: 404, body: { error: "Worker route not found" } };
    } catch (error) {
      return error instanceof RuntimeError
        ? { status: error.status, body: { error: error.message } }
        : {
            status: 503,
            body: { error: "Worker runtime storage unavailable" },
          };
    }
  };
}
